### ISSUE TITLE
[feature request] endpoint query for a specific entity ID

### ISSUE THREAD

**Issue by r-daneel** [internap/almanach#15]
Hi,

I'd like to see an additional endpoint that would allow direct access to an entity:
**GET /entity/{entity_id}**
and/or
**GET /project/{project_id}/entity/{entity_id}**

You'd either get the full object details or a 404 if not existent.
A HEAD request could be used to avoid fetching the whole object if only existence needs to be checked.

Thanks,

**Comment by Marx314** [comment]
HEAD is pending merge, I'll look for a get later on

**Comment by fguillot** [comment]
@r-daneel I submitted a new PR #25 that implements the "GET". At the moment, that returns the history of an entity (all streams), is it ok for your use case?

**Comment by r-daneel** [comment]
@fguillot all streams (aka history) is fine. Let's keep the api clean.

**Comment by mbelang** [comment]
Fixed in PR #25
